name: GITHUB-CICD
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: "17"
          distribution: adopt
          cache: maven
      - name: Build with Maven
        run: mvn clean install
  Selenium-test:
     needs: build
     runs-on: ubuntu-latest
     steps:
       - name: Set up JDK 17
         uses: actions/setup-java@v2
         with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
       - name:  Install Google Chrome # Using shell script to install Google Chrome
         run: |
            chmod +x ./selenium/scripts/InstallChrome.sh
            ./selenium/scripts/InstallChrome.sh 
       - name: Build with Maven
         run: |
              cd selenium 
              mvn test 
 
       - name: upload all test files
         uses: actions/upload-artifact@v2
         with:
           name: selenium-results
           path: ./*
