name: GITHUB-CICD
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: "17"
          distribution: adopt
          cache: maven
  Selenium-test:
     needs: build
     runs-on: ubuntu-latest
     steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: build artifacts
        run: mvn clean package
      - name:  Install Google Chrome # Using shell script to install Google Chrome
        run: |
           chmod +x ./SeleniumGridExecution/scripts/InstallChrome.sh
           ./SeleniumGridExecution/scripts/InstallChrome.sh 
      - name: Build with Maven
        run: |
           cd SeleniumGridExecution
           mvn test
      - name: upload all test files
        uses: actions/upload-artifact@v2
        with:
         name: selenium-results
         path: ./*
